# Generated by Django 2.2.10 on 2020-03-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('model_aircraft', models.CharField(max_length=100)),
                ('range_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('airport_name', models.TextField()),
                ('city', models.TextField()),
                ('coordinates', models.CharField(max_length=30, null=True)),
                ('timezone', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_ref', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('book_date', models.DateField(auto_now=True)),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('flight_no', models.CharField(max_length=10)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHED', 'Scheduled'), ('TIME', 'On Time'), ('DELA', 'Delayed'), ('DEPAR', 'Departed'), ('ARR', 'Arrived'), ('CANC', 'Cancelled')], default='Scheduled', max_length=10)),
                ('actual_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField()),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='airtrans.Airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='airtrans.Airport')),
            ],
            options={
                'unique_together': {('flight_no', 'scheduled_departure')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=20)),
                ('passenger_name', models.TextField(max_length=100)),
                ('contact_data', models.CharField(max_length=100)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(choices=[('ECON', 'Economy'), ('COMF', 'Comfort'), ('BUSI', 'Business')], default='Economy', max_length=10)),
                ('amount', models.FloatField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flight')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Ticket')),
            ],
            options={
                'unique_together': {('ticket_no', 'flight_id')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=100)),
                ('fare_conditions', models.CharField(choices=[('ECON', 'Economy'), ('COMF', 'Comfort'), ('BUSI', 'Business')], default='Economy', max_length=10)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircraft')),
            ],
            options={
                'unique_together': {('seat_no', 'aircraft_code')},
            },
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.PositiveIntegerField()),
                ('seat_no', models.CharField(max_length=5)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idFlight', to='airtrans.TicketFlight')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idTicket', to='airtrans.TicketFlight')),
            ],
            options={
                'unique_together': {('ticket_no', 'flight_id'), ('flight_id', 'seat_no')},
            },
        ),
    ]
