# Generated by Django 2.1.15 on 2020-03-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_ref', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('book_date', models.DateField(auto_now=True)),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
