# Generated by Django 2.2.10 on 2020-03-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='range_seats',
            new_name='distance',
        ),
    ]
