# Generated by Django 2.1.15 on 2020-03-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0002_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_code', models.IntegerField(primary_key=True, serialize=False)),
                ('model_aircraft', models.CharField(max_length=100)),
                ('range_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
                ('timezone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=100)),
                ('fare_conditions', models.CharField(max_length=100)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircraft')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_no', 'aircraft_code')},
        ),
    ]
