# Generated by Django 2.2.10 on 2020-03-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0002_auto_20200314_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='distance',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
