# Generated by Django 2.2.10 on 2020-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0003_auto_20200314_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='timezone',
            field=models.CharField(choices=[('ACST ', 'UTC+9:30'), ('AEST ', 'UTC+10'), ('AKT ', 'UTC−9'), ('ART ', 'UTC-3'), ('AST ', 'UTC-4'), ('AWST ', 'UTC+8'), ('BDT ', 'UTC+6'), ('BTT ', 'UTC+6'), ('CAT ', 'UTC+2'), ('CET ', 'UTC+1'), ('CST ', 'UTC−6'), ('CXT ', 'UTC+7'), ('ChT ', 'UTC−4'), ('EAT ', 'UTC+3'), ('EET ', 'UTC+2'), ('EST ', 'UTC−5'), ('FET ', 'UTC+3'), ('GALT ', 'UTC+6'), ('GMT ', 'UTC'), ('HAST ', 'UTC−10'), ('HKT ', 'UTC+8'), ('IRST ', 'UTC+3:30'), ('IST ', 'UTC+2'), ('IST ', 'UTC+5:30'), ('JST ', 'UTC+9'), ('MT ', 'UTC−7'), ('MSK ', 'UTC+3'), ('MST ', 'UTC+6:30'), ('NFT ', 'UTC+11'), ('NST ', 'UTC-3:30'), ('PET ', 'UTC-5'), ('PHT ', 'UTC+8'), ('PKT ', 'UTC+5'), ('PMST ', 'UTC-3'), ('PST ', 'UTC-8'), ('SLT ', 'UTC+5:30'), ('SST ', 'UTC+8'), ('ST ', 'UTC−11'), ('THA ', 'UTC+7'), ('UTC ', 'UTC'), ('WAT ', 'UTC+1'), ('WET ', 'UTC')], default='UTC', max_length=5),
        ),
    ]
